### ISSUE TITLE
Please explain the meaning of the columns in the *.tab file

### ISSUE THREAD

**Issue by ghost** [danielwuethrich87/Synteny_ortholog_finder#5]
Could you please quickly explain the meaning of every column in the *.annot.tab file?

By the way: I get The following files:
1. database_into
2. folder with:
 a. chrom1.chrom2.blast.annot.tab
 b. reference.phr
 c. reference.pin
 d. reference.psq
--> That's all output I expect, right?

Thx!

**Comment by danielwuethrich87** [comment]
Hi

The chrom1.chrom2.blast.annot.tab and reference.* files are just an intermediate output, that results from the BLAST search. The actual result is printed into the standard output.

Therefore, you have to safe the output like this:

python SynOrF.py strain1_protein.faa strain2_protein.faa strain1_annotation.gff strain2_annotation.gff strain1name.strain2name > actual_output_file

I hope that this helps.

**Comment by ghost** [comment]
Oh, did not check the stdout... sorry!
